### ISSUE TITLE
[BUG] Index page displays incorrect season number

### ISSUE THREAD

**Issue by Umarrii** [thearyadev/top500-aggregator#96]
Hey, was just checking the new season 8 stuff and noticed something that seems wrong.

For First Most Played Support in Americas, the graph shows 151 occurences for Baptiste:
![image](https://github.com/thearyadev/top500-aggregator/assets/29757071/aef1a5b5-f782-4098-b828-329b2a97f8e2)

Whereas when you actually count it manually, it's closer to 26 occurences instead.

I only noticed this because of [this post](https://us.forums.blizzard.com/en/overwatch/t/the-best-supports-right-now-according-to-top-500/869821) where someone manually tallied up the occurences for all supports and went to check myself.

Not sure if this is known already or not but figured I'd post this just in case.

**Comment by Umarrii** [comment]
My bad... I just realised it's showing Season 7 data, the header on the page showed season 8 so I thought it was meant to be showing season 8 data 😅

**Comment by thearyadev** [comment]
there’s actually no season 8 data currently on the site. 

I recently changed the entire front end of the page to a different web framework, and it appears i forgot to fix the season header.

on the [actual season 8 page](https://t500-aggregator.aryankothari.dev/season/8) it will respond with an error. 

sorry about the confusion on this! its been about a day since i made the new front end public, will be fixing this issue soon.

**Comment by thearyadev** [comment]
I’ve merged a temporary fix for this in #97 

thanks for reporting the bug. working on something for so many hours can lead to small things like this being overlooked.

**Comment by thearyadev** [comment]
changes are now live. 😄
